Add support for simba
ajtribick/twofloat pull request #25
Opened 2022-11-26 03:44 UTC by nullchinchilla

2022-11-27 15:07 UTC, ajtribick requested changes
Thanks for this, spotted a few issues but I agree that being able to support nalgebra would be a good thing to have.

2022-11-27 20:09 UTC, nullchinchilla commented
Thanks for all the comments!

Would it be possible for you to edit the code and merge it in? I'm honestly quite unfamiliar with the whole low-level ecosystem surrounding num_traits, simba, and such.

2023-04-06 15:47 UTC, ajtribick commented
Apologies for the delay on this, will take another look after I do the 0.7 release.

2025-07-24 20:06 UTC, ajtribick commented
Thanks for reminding me about this. At the moment, a merge is not possible. I have taken another look and fixed the merge conflict and most of the issues I raised apart from fixing the implementation of `ulps_eq`, which is non-trivial if the high words differ by 1ulp. Will need some more time to figure this out.

2025-07-24 20:23 UTC, ajtribick commented
Closing in favour of #50

2025-07-24 20:23 UTC, closed without merging